development:
  clients:
    default:
      database: dozentron_exercise_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: dozentron_exercise_development
      hosts:
        - localhost:27017

production:
  clients:
    default:
      database: dozentron_exercise_production
      hosts:
        - <%= ENV['MONGO_HOST'] %>